### ISSUE TITLE
Subscriptions not working through GraphiQL

### ISSUE THREAD

**Issue by tkhemani** [apollographql/GitHunt-API#215]
Hi,
I'm using [this article](https://dev-blog.apollodata.com/how-to-use-subscriptions-in-graphiql-1d6ab8dbd74b) and [this video](https://youtu.be/aAwZrBgmnho) as reference to test Subscriptions via GraphiQL, but the web socket is not getting created on creating new subscription (verified via dev tools) and hence, when I post a comment from GitHunt-Angular, it doesn't show up in GraphiQL. Am I missing something here?

**Comment by Urigo** [comment]
@tkhemani yes, that's because we haven't upgraded it to the newest version of `graphql-server-express@0.7.0` - https://github.com/apollographql/GitHunt-API/blob/master/package.json#L54

We would love a PR that updates a bunch of the dependencies and verifies that everything works.
Would you consider doing that?  I can help of course

**Comment by tkhemani** [comment]
Updated to `graphql-server-express@0.7.0` but no luck. Then ran [ncu](https://www.npmjs.com/package/npm-check-updates) and updated all packages, but Subscriptions via GraphiQL still doesn't work.

**Comment by Urigo** [comment]
sorry, I forgot I haven't added some stuff...
I've fixed it [here](https://github.com/apollographql/GitHunt-API/pull/217)
